accounts/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views
app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('signup/',views.signup,name='signup'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('add_profile/',views.create_profile,name='add_profile'),

    #path('password_change/',auth_views.PasswordChangeView.as_view(),name='password_change'),
    #path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    #path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),

]

olx/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('products/',include('product.urls',namespace='products')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('',include('home.urls',namespace='home')),

]
urlpatterns+=static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)






'''
accounts/ login/ [name='login']
accounts/ logout/ [name='logout']
accounts/ password_change/ [name='password_change']
accounts/ password_change/done/ [name='password_change_done']
accounts/ password_reset/ [name='password_reset']
accounts/ password_reset/done/ [name='password_reset_done']
accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/ reset/done/ [name='password_reset_complete']
admin/
products/
^static/(?P<path>.*)$
^media/(?P<path>.*)$

'''

product/urls.py
from django.urls import path
from . import views
app_name = 'products'

urlpatterns = [
    path('',views.productlist,name='product_list'),
    path('add_product/', views.add_product, name='add_pro'),
    path('update_product/<str:slug>/<int:id>/',views.update_product, name='update_product'),
    path('add_product_image/<str:slug>/<int:id>/', views.add_image_product, name='add_product_image'),
    path('<str:category_slug>/',views.productlist,name = 'product_list_category'),
    path('details/<str:slug>/<int:id>/',views.productdetail,name = 'product_detail'),
    path('delete/<str:slug>/<int:id>/',views.delete_product,name = 'delete_product'),


]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import pre_save,post_save
import os
import random

# Create your models here.



def photo_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'
    randomstr = ''.join((random.choice(chars)) for x in range(10))
    return 'user_images/{userid}/{basename}{ext}'.format(userid=instance.user.id,
                                                                             basename=basefilename,
                                                                             randomstring=randomstr, ext=file_extension)


class User_Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    phone = models.IntegerField(blank=True,null=True)
    address = models.CharField(blank=True,null=True,max_length=400)
    user_img = models.ImageField(upload_to=photo_path,blank=True,null=True)



    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import User_Profile

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.',widget=(forms.EmailInput(attrs={'class':'come_class'})))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = User_Profile
        fields = ('phone','address','user_img')



class EditUserDate(forms.Form):
    first_name = forms.CharField(max_length=50,required=False,help_text='First_name')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.',widget=(forms.EmailInput(attrs={'class':'come_class'})))
    phone = forms.CharField(max_length=30, required=False, help_text='Optional.')
    address = forms.CharField(max_length=253,required=False, help_text='Optional.')
    user_img = forms.ImageField()

accounts/views.py
from django.contrib.auth import login,authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect,HttpResponse

from accounts.models import User_Profile
from .forms import SignUpForm, ProfileForm, EditUserDate
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from product.models import Product



# Create your views here.

def login_view(request):
    if request.method =='POST':

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return HttpResponseRedirect('/')
        else:
            return HttpResponse('<center><h1>Your User Name Or Password Is not avilapel</h1></center>')
    else:
        return render(request,'registration/login.html',{})




def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('accounts:add_profile')
    else:
        form = SignUpForm()
    return render(request, 'registration/register.html', {'form': form})

@login_required
def create_profile(request,user=None):
    if request.method == "POST":
        form = ProfileForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.phone = form.cleaned_data.get('phone')
            new_form.address = form.cleaned_data.get('address')
            new_form.user_img = form.cleaned_data.get('user_img')
            new_form.save()
            return redirect('/')
    else:
        form = ProfileForm()
    context = {
        'form':form
    }
    return render(request,'registration/create_profile.html',context)




def dashboard(request):
    user_products = Product.objects.all().filter(owner_id=request.user.id)
    user_profile = User_Profile.objects.all().get(user=request.user.id)
    context = {
        'products':user_products,
        'user_profile':user_profile
    }
    return render(request,'dashboard.html',context)




def edit_user_profile(request):
    pass

accounts/templates/dashboard.html
{%extends 'base.html'%}
{%load static%}
{% load bootstrap4 %}

{% block style %}
  #dashboard .container .dash-head{
        margin-top: 65px;
        margin-bottom: 65px;
          }
  #dashboard .container .dash-docs{
    font-size: 20px;
    text-align: center;
    margin: 30px;
}
  #dashboard .container table{
    height: 100%;
    width: 100%;
    margin: 9%;
    padding: 0;
    margin-left: 0;
    margin-top: 0;
}

  #dashboard .container table tr td a{
    color: #fff;
    font-size: 17px;
    background-color: #01a185;
    padding: 10px 7px;
    margin-right: 2%;
}
  #dashboard .container table tr td .delete{
    background-color: #f00;
}
{% endblock %}

{%block body%}


  <section id="dashboard" class="trend-ads">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
            <div class="image" style="    width: 20%;
    margin: auto;
    margin-top: 5%;">
                {% if user_profile.user_img %}
            <img src="{{ user_profile.user_img.url }}" style=" width: 100%;border-radius: 50%;">
                {% else %}
                    <img src="{% static 'images/1.jpg' %}" style=" width: 100%;border-radius: 50%;">
                {% endif %}
            </div>
                <h2 class="dash-head">Welcome {{ request.user.username }}</h2>
          <p class="dash-docs">Here are the property listings that you have inquired about</p>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Products</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
                {% if products %}
                {% for product in products %}
                <tr>
                <td>{{forloop.counter}}</td>
                <td>{{ product.name }}</td>
                <td>
                  <a class="btn btn-light" href="{% url 'products:product_detail' product.slug product.id %}">View Products Detail</a>
                  <a class="btn btn-light" href="{% url 'products:add_product_image' product.slug product.id %}">Add More Image</a>
                  <a class="btn btn-light" href="{% url 'products:update_product' product.slug product.id %}">update Product</a>
                  <a class="btn btn-light delete" href="{% url 'products:delete_product' product.slug product.id %}">delete Product</a>
                </td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                  Products Empty
                </tr>
                {% endif %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

accounts/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post">
        {{ form }}
        {{ form2 }}
    </form>
</body>
</html>

accounts/templates/login.html
{%extends 'base.html' %}
{%load static%}
{%block body%}
	 <section>
			<div id="page-wrapper" class="sign-in-wrapper">
				<div class="graphs">
					<div class="sign-in-form">
						<div class="sign-in-form-top">
							<h1>Log in</h1>
						</div>
						<div class="signin">
							<div class="signin-rit">
								<span class="checkbox1">
									 <label class="checkbox"><input type="checkbox" name="checkbox" checked="">Forgot Password ?</label>
								</span>
								<p><a href="#">Click Here</a> </p>
								<div class="clearfix"> </div>
							</div>

						<form method="post">
							{%csrf_token%}
							{{form.as_p}}
							<input type="submit" value="login">
						</form>
						</div>
						<div class="new_people">
							<h2>For New People</h2>
							<p>Having hands on experience in creating innovative designs,I do offer design 
								solutions which harness.</p>
							<a href="register.html">Register Now!</a>
						</div>
					</div>
				</div>
			</div>


</section>
		 {%endblock%}